version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=LamborghiniLover
      - MYSQL_DATABASE=rentmycar
      - MYSQL_USER=user
      - MYSQL_PASSWORD=LamborghiniLover
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysqldb:/var/lib/mysql
  rentmycar-api:
    container_name: rentmycar-api
    image: rentmycar/api:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - 80:8080
    restart: always

volumes:
  mysqldb: